class MessagesController < ApplicationController
  def create
    @element = Element.find(params[:element_id])

    @message = @element.messages.build(message_params)

    @message.role = "user"

    if @message.save
      response = llm_element_update
      @element.messages.create(
        role: "assistant",
        content: response.content
      )

      redirect_to element_path(@element)

    else
      @messages = @element.messages.order(:created_at)

      render "elements/show", status: :unprocessable_entity
    end
  end

  def llm_element_update
    ruby_llm_chat = RubyLLM.chat(model: "claude-sonnet-4-6")
    ruby_llm_chat.with_tool(UpdateElementTool)
    ruby_llm_chat.with_instructions("#{Element.update_system_prompt}\n#{update_theme_context}")
    ruby_llm_chat.ask(@message.content)
  end

  def update_theme_context
    "You are updating an existing component with the id: #{@element.id}, the name: #{@element.name}, which is being generated by this html code (#{@element.html_code}) and this css code (#{@element.css_code}) under a user definined theme with the name #{@element.theme.name} and with a description of #{@element.theme.specs}."
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end
