class AiUpdateJob < ApplicationJob
  queue_as :default

  def perform(message)
    element = message.element
    update_theme_context = "You are updating an existing component with the id: #{element.id}, the name: #{element.name}, which is being generated by this html code (#{element.html_code}) and this css code (#{element.css_code}) under a user definined theme with the name #{element.theme.name} and with a description of #{element.theme.specs}."
    ruby_llm_chat = RubyLLM.chat(model: "claude-sonnet-4-6")
    ruby_llm_chat.with_tool(UpdateElementTool)
    ruby_llm_chat.with_instructions("#{Element.update_system_prompt}\n#{update_theme_context}")
    response = ruby_llm_chat.ask(message.content)
    element.messages.create(
      role: "assistant",
      content: response.content
    )
  end
end
